name: Subgraph CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: |
          cd subgraph
          yarn
      - name: Generate code
        run: |
          cd subgraph
          yarn codegen
      - name: Build
        run: |
          cd subgraph
          yarn build
      - name: Run tests
        run: |
          cd subgraph
          yarn test
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
